### ISSUE TITLE
ROADMap

### ISSUE THREAD

**Issue by kipkurui** [BioinfoNet/FAIRGenomics#1]
**First**
- [x] Key contact persons identified in research and academic institutions
- [x] A clear Roadmap and Theory of Change for the project developed
- [x] Completed research and surveys to understand the exact genomic data storage, sharing and reuse policy needs

**Deliverables:**

    - [ ] First medium article published
    - [ ] First peer review article submitted

- [ ] Sensitize and promote the need for FAIR genomic data policies at institutions, starting with icipe
- [ ] Attract Computer Scientists to Biomed research via at least 5 seminar talks within CS offering Universities in Nairobi
    - [ ] Work on first genomic data storage and reuse policy draft
    - [ ] Collaborate with computer scientists to develop projects in the intersection of computer science and Biomedical research. Leverage my Biomed networks to collaborate on this.
- [ ] Build a community of project participants through meetups and working together
- [ ] Promote the adoption of the FAIR genomic data framework in research institutions, starting with icipe
    - [ ] Explore a genomic data storage infrastructure with CS and open science community to adapt

***Finally***

- [ ] Look-back and review the progress made through the fellowship
    - [ ] Continue with community building via meetups
    - [ ] Medium article reflecting on fellowship journey, challenges, lessons and key outcomes
